### ISSUE TITLE
Failed to parse appKeyConfig

### ISSUE THREAD

**Issue by FREEZX** [Uepaa-AG/p2pkit-quickstart-android#7]
Hi there.
I'm in the process of developing a small cordova plugin for p2pkit for my own needs, and i'm hitting the following error when running enableP2PKit(apiKey):
```
12-07 14:37:38.580 24657-24673/? E/a: Failed to parse appKeyConfig
                                      org.json.JSONException: Value 㝶��xw� of type java.lang.String cannot be converted to JSONObject
                                          at org.json.JSON.typeMismatch(JSON.java:111)
                                          at org.json.JSONObject.<init>(JSONObject.java:160)
                                          at org.json.JSONObject.<init>(JSONObject.java:173)
                                          at ch.uepaa.p2pservices.a.a(SourceFile:73)
                                          at ch.uepaa.p2pservices.k.<init>(SourceFile:45)
                                          at ch.uepaa.p2pservices.d.a(SourceFile:83)
                                          at ch.uepaa.p2pservices.j.register(SourceFile:180)
                                          at ch.uepaa.p2pkit.IServicesBinding$Stub.onTransact(SourceFile:62)
                                          at android.os.Binder.execTransact(Binder.java:446)
```

My first suspicion was that i was sending a malformed apiKey, but upon further inspection, my app key looks ok. Any pointers about what might be causing this?

**Comment by FREEZX** [comment]
If you are interested, here's the source code for my plugin:
https://github.com/FREEZX/p2pkit-cordova

and here's how i'm using it:
```
cordova.plugins.p2pkit.isP2PServicesAvailable(function success() {
    cordova.plugins.p2pkit.enableP2PKit('<apikeyhere>');
  }, function error(code) {
    if(code === 1) {
      ons.notification.confirm({message: 'The p2p services package is missing. Install it now?'}).then(function(success){
        if(success) {
          if(device.platform == 'Android') {
            cordova.plugins.market.open('ch.uepaa.p2pservices');
          }
        }
      });
    }
  });
```

**Comment by Schlaepfer** [comment]
Hi FREEZX

Thank you very much for reporting this issue. The error won't have any impact on your app, so you can ignore it. With the next update (1.3.9) this error will be gone.

Cheers!
